### ISSUE TITLE
Would Object.keys suffice instead of lodash.keys?

### ISSUE THREAD

**Issue by MHerszak** [dashed/shallowequal#5]
I am currently working with Meteor and we use `PureRenderMixin` to render or not when properties change. Facebook released an update to use `shallowCompare` mixin which makes use of shallowequal and this has a dependency to lodash.keys. Meteor however applies Underscore and I would love to utilize it more often if possible. But to be more dependency free, would `shallowequal` work with Object.keys? It seems to apply the same logic and return an array of keys.

Update: Object.keys is not working on IE-version lower than 9. But there are polyfills.

**Comment by dashed** [comment]
@MHerszak hi, I don't think react use this `shallowequal` module. If I recall, they use this shallowequal: https://github.com/facebook/fbjs/blob/4113922e7963d73566385039b6948e455e508d87/packages/fbjs/src/core/shallowEqual.js

So, these lines may be somewhat misleading within react's source code: 

```js
// ...
var shallowEqual = require('shallowEqual');
// ...
```

https://github.com/facebook/react/search?utf8=%E2%9C%93&q=shallowequal

----

To double check, I `npm install --save react` on an empty npm project, and I get this output of react's dep tree:

```
└─┬ react@15.3.2
  ├─┬ fbjs@0.8.4
  │ ├── core-js@1.2.7
  │ ├── immutable@3.8.1
  │ ├─┬ isomorphic-fetch@2.2.1
  │ │ ├─┬ node-fetch@1.6.1
  │ │ │ ├─┬ encoding@0.1.12
  │ │ │ │ └── iconv-lite@0.4.13
  │ │ │ └── is-stream@1.1.0
  │ │ └── whatwg-fetch@1.0.0
  │ ├─┬ promise@7.1.1
  │ │ └── asap@2.0.4
  │ └── ua-parser-js@0.7.10
  ├─┬ loose-envify@1.2.0
  │ └── js-tokens@1.0.3
  └── object-assign@4.1.0
```

**Comment by MHerszak** [comment]
Thanks for you clarification!
