### ISSUE TITLE
Breaking webpack production builds

### ISSUE THREAD

**Issue by magalhas** [dashed/shallowequal#8]
Uglify does not support `let` statements. Due to the recent release many webpack production builds are failing because of this.

**Comment by gimdongwoo** [comment]
Right!

```
ERROR in main-df07a8a05e193c746606.js from UglifyJs
Unexpected token: name (ret) [./~/shallowequal/index.js:3,0][main-df07a8a05e193c746606.js:91645,8]

```

**Comment by bradyhigginbotham** [comment]
This is a big breaker for us. The `let` key needs to be replaced.

**Comment by whymarrh** [comment]
Indeed, I am running into this issue as well. I can confirm that replacing `let` with `var` fixes the build (I can't speak to the correctness, as I've not tested it).

**Comment by gimdongwoo** [comment]
The react-side-effect was released from 1.1.0 to 1.1.1 two hours ago, using shallowequal@1.0.0.

**Comment by seansean11eis** [comment]
Also seeing breaking webpack builds today and tracked it down to this package update.  For the time being I'm going to lock this down to 0.2.2 in our code.

**Comment by bsthomsen** [comment]
It's also breaking builds on my build server.

**Comment by dashed** [comment]
Ugh. I knew something would break when I refreshed the project. 😞 

I'll use var in favour of let and const; and push the update out asap.

**Comment by lourd** [comment]
I just published 1.1.2 of react-side-effect rolling back the shallowequal dependency to resolve the broken builds.

No good deed goes unpunished, right? 😅  Thanks for prompt reply @dashed

**Comment by dashed** [comment]
I released `v1.0.1` with  `var` switched out in favour of `let` and `const`. 

Hopefully this shouldn't break webpack builds.

**Comment by whymarrh** [comment]
It happens to the best of us! Thank you for your work @lourd an @dashed.

**Comment by lourd** [comment]
You're welcome 👊🏼 Just published 1.1.3 of react-side-effect which uses 1.0.1 of shallowequal

**Comment by gimdongwoo** [comment]
Build succeeded.
react-side-effect@1.1.3
     └── shallowequal@1.0.1

**Comment by bradyhigginbotham** [comment]
Great, quick work by both projects. Kudos, @dashed and @lourd!

**Comment by dashed** [comment]
@magalhas I'm wondering if the update fixes your uglify issues for your builds (as others seem to be reporting).

**Comment by magalhas** [comment]
Yes it's working fine now 👍

**Comment by dashed** [comment]
@magalhas awesome to hear. 👍  will close this issue.
